eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
    #  defaultZone: http://localhost:8080/service-registery/eureka
  instance:
       hostname: localhost
       prefer-ip-address: false
#    hostname: 192.168.0.108
name: 'wakeel malik git'